version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./pgsql-data:/var/lib/postgres/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
